configuration:
  env:
    -name: APP_GOOGLE_PROGECTID
      value: "randomnumberagent2-brk9"
    -name: APP_GOOGLE_PRIVATEKEYID
      value: "c881d921eb02a4cfeef3b91144cabda3f1df46a4"
    -name: APP_GOOGLE_PRIVATEKEY
      value:  "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC581OPWS9dZMFt\ngbFGyinjdH3Zz/gr1xAkBS0tBC4eTQ/kU+ftufa6+zEUHFXlc4/m2jAS3houXv8k\nTxdGyoNetIFlbfOnbDoBxETApUU5TpEElRrEdbDDsXflPomg/7E4DLd8gjRAme3N\n8I87p8ssl2wtl0mEixL7I27bv4Bx/No85d4LAZL+GYz452GjBjsAeewZ+h5bckzI\nGIsngvZ4F3R54Gd6Z8PIaWVT6FswELjcNNeUVwC7Cfec8MI6u021lcLt391S8Diw\nGKpvY4jTRoGfBBH8AMUOxlutxBrPZ1hsgoHoA/es4tdzF30rAG20F6dADuF60ecd\nHYoGCxzHAgMBAAECgf8UKC5hotGI6o2V63EKVHXS0MaMAVjiJa+KhZtXdvulzB9/\n6SqUm3r8cIjtNjfGA7XfTQI6jyDarz3/Q2WrGmiw0tpxGb7dc0OHrmq5fPlp5cLB\nKeFawa1vwx3dFO1Ty/dcPe4TataKzKzQ1/vr85Ux0Y4sNRxr7RIBRHl95oradh+7\nhV0lbG+YcRh9QY7ZXXTvWe0XqSQOzXJ6uRAqV7jp8+R1uqw4DpAU2VEgZ+1rjkLK\nyhGAsIKMoJGyTc3V0UiRaGBwnnWMFwwHSSo9gH1SCSj87s6g9w7S/1k2kNTDPzLN\nBVekMsPA7kGO4IM0qnnr5i2n7m46/c7fi+WjaIECgYEA4CLEq5Sjwufwlwh7Pdjx\n/bOlBL5uH22Ie0IhyKZeVFAGYsOi1lBJI/7kNPshscPG3kxJ4/6LwM14hMzw1b6N\nK3O1X2uF2ag302M/obdaMG7ky4mo6eqjRW4xgf143A2uFQ0+YhBQTH6Lhkwl2ehT\nPklkFkdQ4xz8gY5KvsLfWKMCgYEA1GLWBZqQqyA2ZaM37UqRT9AGwEZmBeCjVDPx\nmsURXKHiQS/p3gHwOvSgICO8KQc9MbFSER8GF2+1NiQpCsJcMJW7y5ntTEUEZCLq\nFGWXFGWRVnlhgPxCFk2V24gHNeqA6OkqZFjF4A47lDI/wbgNkljtg/hZZE2sP+hS\n/n45OY0CgYBOdF0bIiBgbQeOFm3tLC8oeuVcT7wETDblzjQ9I98I7CoQECLDmb7A\nVsxSr0UQEFNgJJwIrmUEy+dPtNzoNJb9ircF+4ESuwsvdyIi3Sc4pNh5VmpF1tfn\nybaSpcLUZAV3YPdhJAy3eeQk0iq9p9DbkJz0H2p01QSd5MzNETFUuQKBgQC68/mD\nW0iHakaX9zHuzhnVkL+wlweNmu0K3OKLI3eh+9onGZ8azsgBjX46bFpgH0AtsvIT\noiSBktKHwxLhpq7yEYwKsAdjgMlZwCYfKEHyMWnbHePHX8ZozYjhgv8d5bvtyfmH\n9WDRVpX5YLYgtvwzW9ZPudguY/UBGGeeH8wNrQKBgQCLyTfhVMaJm0kg/zEX5zto\ngBY32VDdc5nWqhZ6EpVaAUnBdA6+vC1kDqbD+x/H4FqYWnkBTwnLJvIh1iVPme9D\nSYvfg/2Z40n9a7V7eM37j6ZgOWFm+6V1VC+KnCv0wDLnLMVKtEiE2s4o7xgtVPyW\nv+V9q1gDNO+fPWmv7k44bA==\n-----END PRIVATE KEY-----\n",
    -name: APP_GOOGLE_CLIENTEMAIL
      value: "default-dialogflow-service-acc@randomnumberagent2-brk9.iam.gserviceaccount.com"
    -name: APP_GOOGLE_CLIENTID
      value: "112981335197819603054",
    -name: APP_GOOGLE_CLIENTX509CERTURL
      value: "https://www.googleapis.com/robot/v1/metadata/x509/default-dialogflow-service-acc%40randomnumberagent2-brk9.iam.gserviceaccount.com"

        # Provvisoriamnete le impostazioni dell'agente Dialogflow del sito sono le stesse dell'agente mobile;
        #  se e quando si dovrà estendere le funzionalità del chatbot al secondo canale, e l'agente IB verrà effettivamente
        #  creato e definito, e si ovrà poi invocarlo, modificare le impostazioni di conseguenza
        - name: IB_GOOGLE_PROJECTID
          value: "ispgcdcci0t019"
        - name: IB_GOOGLE_PRIVATEKEYID
          value: ""
        - name: IB_GOOGLE_PRIVATEKEY
          value: ""
        - name: IB_GOOGLE_CLIENTEMAIL
          value: ""
        - name: IB_GOOGLE_CLIENTID
          value: ""
        - name: IB_GOOGLE_CLIENTX509CERTURL
          value: ""

        - name: GOOGLE_SCOPE
          value: "https://www.googleapis.com/auth/dialogflow https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/devstorage.read_write"
