spring:
  application:
    name: RIBBONBALANCELOADER

chatbot:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9000, localhost:8090
    ServerListRefreshInterval: 15000

server:
  port: 9090